Fix PA_HEADER_DEFINES with clang
PA_HEADER_DEFINES uses "int main()" unnecessarily. Autoconf already
provides the function header, all that's needed is the function body.

gcc 10 issues a warnings for the nested main():

conftest.c:77:5: warning: 'main' is normally a non-static function [-Wmain]
conftest.c:77:5: warning: declaration of 'main' shadows a global declaration [-Wshadow]

But clang 10 rejects that code
conftest.c:77:1: error: function definition is not allowed here

As a result, F_SETLK is considered missing from fcntl.h and locking is
not enabled.

Signed-off-by: Pavel Roskin <plroskin@gmail.com>